### ISSUE TITLE
Fix broken CI

### ISSUE THREAD

**Issue by BGluth** [mir-protocol/evm-tests#32]
Currently the CI is broken, and from a quick skim, it looks like there's a plonky2 version mismatch somewhere?

**Comment by Nashtare** [comment]
Hmm I also ran into it locally as well, seems like the patch section isn't working properly somehow. Not sure why though

**Comment by Nashtare** [comment]
A temporary not so pretty fix, at least until `plonky2_evm` is on crates.io could be to have a dedicated branch for this repo (and possibly the cluster), where there the `Cargo.toml` of the evm crate points to the local plonky2 (i.e. with `path = "../plonky2"`). This should alleviate the problem.
