### ISSUE TITLE
Test parser is missing some tests

### ISSUE THREAD

**Issue by Nashtare** [mir-protocol/evm-tests#33]
Folders with subfolders like Shanghai / VMTests seem to be ignored when running eth_test_parser as they don't have any files at their top level. 
As they contain dedicated tests for the logic / arithmetic STARK modules, and tests for the LOG opcodes that will be integrated soon (cf https://github.com/mir-protocol/plonky2/pull/1097), we'd probably want to fix this.

**Comment by BGluth** [comment]
I should have a few free cycles in the next 24 hours and I'll take a look at this. :+1:
